### ISSUE TITLE
Simulation of Jet flow

### ISSUE THREAD

**Issue by sumit-sp** [HiFiLES/HiFiLES-solver#132]
I am trying to do simulation for jet flow but I am getting following error.

  Iter            Res[Rho]          Res[RhoVelx]    Res[RhoVely]      Res[RhoE]          Fx_Total       Fy_Total
 30000       0.00096002     0.00236180     0.00064232     0.01007507           -nan           -nan
Writing Tecplot file number 30000 on rank 0
## In calculation of plot_quantitiy mach: Fatal error 'NaN' at ../src/eles.cpp:4525

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

I am attaching input file and an image that shows how I have chosen boundary conditions.
Please help if I'm doing something wrong.
![untitled](https://cloud.githubusercontent.com/assets/21123230/19016039/9d109844-882d-11e6-921f-0e5d7580d64a.png)
[input_flatplate_a.docx](https://github.com/HiFiLES/HiFiLES-solver/files/504541/input_flatplate_a.docx)

**Comment by mlopez14** [comment]
Thanks for the detailed graph and the input file! In the input file I see you're selecting a case with Re = 1e5 and Ma = 0.5. Because the initial flow is uniform, there will be a strong initial "vacuum" forming at the "adiabat_fix" walls. It's as if the fluid were traveling at Ma = 0.5 and suddenly a wall appeared.

I would recommend starting with very mild initial conditions to make the initial appearance of the wall less sudden. More explicitly, set Re = 100, Ma = 0.01, p = 2

If this setup doesn't work, set p = 1. If the simulation runs, save the restart file, increase the Re and Ma values and restart.

Also, the "sub_out_simp" boundary conditions will be trying to keep the fluid moving at the specified Re and Ma values. I would suggest setting those three boundaries to either "adiabat_fix" or "slip_wall". To prevent pressurizing your domain too much, place the boundaries far away from the jet.

Let us know how it goes!

**Comment by sumit-sp** [comment]
this may be a stupid question, but what is p? is it pressure
I mean in the input tutorial there is no such thing.
and one more question how to set required ambient/far field conditions.
