### ISSUE TITLE
Questions about LES

### ISSUE THREAD

**Issue by jmaximelv** [HiFiLES/HiFiLES-solver#52]
Hi all,
I've some questions about the LES,
1. The filter process. I know the standard LES filter process is realized by a convolution. But I cannot understand  what HiFiLES do. It works like: U_{filtered}=F_{filter matrix}*U_{origin}. I hope someone can give me some explications about this process and about the generation of the filter matrix. Or just give some reference papers and/or books.
2. In the code (method "CalcResidual" in solver.cpp), there are some comments before the call of the method "calc_sgs_terms" like "If at first RK step and using certain LES models, compute some model-related quantities". But I think the filter process is active in every RK step.
3. The balance between the order of approximate polynomial and the mesh size? It is better to use high order polynomial and coarse mesh or the opposite? Is there any suggestion about the polynomial order and the mesh size?

Thanks in advance!
Maxime

**Comment by jrbull** [comment]
Maxime,

Thanks for your questions.

1. The code solves the ‘implicitly’ filtered equations, i.e. the convolution in the LES equations is done by the discretisation on the grid. However, in the similarity model an additional ‘explicit’ filter is also performed to get terms like $\overline{\bar u_i \bar u_j}$ (apologies for the Latex notation). There is one exception: in the SVV (spectral vanishing viscosity) model is selected, the code solves the explicitly filtered equations. However, this model is not recommended at present as it is still under development. The safest choice right now is the WALE model, which does not require any explicit filtering at all.
There are several different types of filter in the code, some of which are only available for certain element types. Only the modal Vandermonde filter is available for all element types.

2. You are right that the calc_sgs_terms subroutine is called every RK iteration. This is not necessarily a bad idea and the computational overhead is minimal. However, I will make sure to correct the comment.

3. In general, higher polynomial orders (p>5) are unstable for realistic problems due to the appearance of aliasing errors. We are working on methods to control these instabilities. For now, p=3 and p=4 should be stable for LES. p=5 may be OK in some cases. As a rough guide, the total degrees of freedom (elements x solution points per element) should be similar to the number of elements required in a mesh for a 2nd order finite volume simulation of the same problem. However, mesh quality is of very high importance so you may have to refine the mesh near complex geometry.

Let us know how you get on.
Cheers,
Jonathan

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by jmaximelv** [comment]
Hi Jonathan,
Thanks!!  Just a little more question about the meaning of  "the computational overhead is minimal" in your response.

Best regards,
Maxime

**Comment by jrbull** [comment]
If you look at the calc_sgs_terms subroutine, you’ll see that it contains a few loops over all the degrees of freedom (eles*upts*fields) and a few calls to the BLAS matrix multiplication library. The CPU time taken for these calculations is small compared to the total CPU time for a timestep.

Postdoctoral Scholar
Dept of Aero/Astro Engineering
Stanford University

**Comment by jmaximelv** [comment]
Thanks!  I thought it was because that more filter process will accelerate the solution converge to a smooth state. So that the overall computation effort is minimal.  thanks.
Sincerely,
Maxime
