### ISSUE TITLE
about mesh

### ISSUE THREAD

**Issue by paipaizhu** [HiFiLES/HiFiLES-solver#56]
Hi,all
I have question about mesh.
1,why the amount of grid is so little that cannot keep Geometric shape.
2,when i use SA model,40000 mesh, The calculation time is very long.why?
3,In tecplot,why the amount of mesh become large?when the amount of mesh is 35000,it become about 800000.why?
Best regards
zhu

**Comment by mlopez14** [comment]
1. I am not sure what you mean by question 1. Is your question about why use a coarse mesh?

2. Correct, the SA model introduces some very stiff terms. Ideally the RANS equations would be solved with an implicit solver. We still have not implemented that capability. The code is meant to capture vorticity really well, not converge to a steady RANS solution really fast.

3. The solution inside each element is being represented by a polynomial. In order to plot the result of simulations, the code samples the polynomial in different locations. These locations are the "plot points"; you can control how many appear inside each element in the input file.

**Comment by paipaizhu** [comment]
Thank for your reply mlopez14.
1,Yes,why use a coarse mesh? we cannot keep Geometric shape.
2,your mean is when cannot use SA model to calculation NASA 0714(i used).
3,That's what I thought，just cannot for sure,thank you !
Best regards
zhu

**Comment by paipaizhu** [comment]
2,your mean is we cannot use SA model to calcution NASA0714(i used)

**Comment by mlopez14** [comment]
1. It is possible to preserve the geometric shape with high-order elements. Gmsh is able to produce elements of this type.
2. The SA model will limit the time-step you can take severely. The code has been verified for low Re flows over airfoils, so you know you'll get appropriate results for such cases. We're working on the ability to run high-Re cases.

**Comment by paipaizhu** [comment]
Thanks for  your reply,mlopez14.
I use pointwise to produce mesh ,can you send me a NACA 0012 mesh?My email is 2528122150@qq.com,
Best regards
zhu

**Comment by JacobCrabill** [comment]
Hi Zhu,

I don't know if any of the other developers has a nice-quality NACA0012 mesh available, but you can find two .geo files (Gmsh input files) for one [here](http://jcrabill.weebly.com/errata.html) (at the bottom of the page).  [Gmsh](http://geuz.org/gmsh/) is freely available, and as Manuel mentioned, it can very easily output curved-edge elements.  Additionally, it's quite easy to modify a mesh to your liking by adjusting the parameters in the .geo file.

-Jacob

**Comment by paipaizhu** [comment]
Thanks for your reply,I will try!
