### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by zhan1457** [HiFiLES/HiFiLES-solver#87]
Hi,
I am testing the code. It stops after first iteration and showes the following information: 

Program received signal SIGSEGV, Segmentation fault.
0x0000003c46c75f85 in malloc_consolidate () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.9.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64

I think it may because the code wants to use the memory that has not been allocated.  Have you guys encountered similar cases before? Or have you ever set any limitation for the variables you used?

**Comment by mlopez14** [comment]
This is strange; we have not encountered segmentation faults.

This has happened to us when the MPI installation is not configured properly. Did you run with code with MPI? Do you encounter this problem when using just one processor?

**Comment by zhan1457** [comment]
I think I solve the problem. I am running a 3D RANS case (added by myself), so the n_fields should be 6. However, the norm_residual is defined to only have the length of 5 in HiFiLES.cpp. I change the number to 6 and no segmentation fault occurs. Thanks all the same.

**Comment by jewatkins** [comment]
Let me know if you run into any more problems trying to run a 3D RANS case. I tried to make the code general so that you only need to add the source terms but I may have missed a few spots where n_fields needs to be changed.

I'd also be interested in any other problems you may have encountered for future implementation.

Thanks!
-Jerry
