### ISSUE TITLE
Fatal error 'Unable to open cubature file' 

### ISSUE THREAD

**Issue by popstar0426** [HiFiLES/HiFiLES-solver#93]
Hi:
    I tried to run HiFiLES on a cluster.
    However, I met a error:
     Final  16-way Cut:   3986 	Balance: 1.041 
After parmetis 
reading vertices
done reading vertices
Setting up mesh connectivity
Done setting up mesh connectivity
reading boundary conditions
Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75
Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75
Fatal error 'Unable to open cubature file' at ../src/cubature_quad.cpp:75

Best regards!

**Comment by JacobCrabill** [comment]
This is most likely due to the environment HIFILES_HOME not being set.  When running on a cluster, you'll need to edit your .bashrc (or .cshrc, or whichever terminal language is in use) to set the variable HIFILES_HOME, so that when the cluster submits your job on the compute node(s), that environment variable will be set before HiFiLES is run.

If that doesn't fix the problem, you could always hard-code the path to the folder "HiFiLES-solver/" within the code, either as an absolute path, or a relative path to where you are running the solver.
