### ISSUE TITLE
Simulation of supersonic flat plate

### ISSUE THREAD

**Issue by hzhf** [HiFiLES/HiFiLES-solver#96]
The simulation of inviscid supersonic air flowing over flat plate was tested. It ran on multi-CPUs(MPI)
It was always failed, and I could not find out any problems.

The flow parameters were as below:
  Ma=5.0 AOA = 0.0;                        Ma=5.0 AOA = -20.0;
rho_bound = 0.0394659;                 rho_bound = 0.0394659;            
u_bound   = 1492.2900;                  u_bound   = 1402.2939;
v_bound   = 0.0;                              v_bound   = -510.3932;
w_bound   = 0.0;                             w_bound   = 0.0;
p_bound   = 2511.01;                     p_bound   = 2511.01;

'flatplate_a3-125-2s.neu' in the testcase was used as the mesh file needed by the simulation.
The bound conditions of mesh 'flatplate_a3-125-2s.neu' were changed as below:
'Slip_Wall'        was changed to  'Slip_Wall';
'Adiabat_Fix'     was changed to  'Slip_Wall';
'Char'                was changed to  'Sup_In';
'Sub_Out_Simp' was changed to  'Sup_Out';
'Sub_Out_Simp' was changed to  'Sup_Out'.

Case 1: AOA=+0.0
when setting dt_type = 0, the running would be failed.
when setting dt_type = 1, the running would be normal and successful.
you can look at the two running-log files where all-round datas were in.

Case 2: AOA=-20.
The residual error of Rho*Vely was always increasing 
no matter what I did, such as changing CFL or dt in the control file.

run_inviscid_AOA=+00_dt_type=1:
![run_inviscid_aoa 00_dt_type 1](https://cloud.githubusercontent.com/assets/14209638/9819716/43d621de-58e2-11e5-97d4-b4ba18efe477.png)
run_inviscid_AOA=+00_dt_type=0:
![run_inviscid_aoa 00_dt_type 0](https://cloud.githubusercontent.com/assets/14209638/9819772/9044bf26-58e2-11e5-8b60-befbc5188e4f.png)
run_inviscid_AOA=-20_dt_type=1:
![run_inviscid_aoa -20_dt_type 1](https://cloud.githubusercontent.com/assets/14209638/9819802/b56b66ce-58e2-11e5-8cd0-a45cf6ea14ed.png)

![input_1](https://cloud.githubusercontent.com/assets/14209638/9819828/d881a420-58e2-11e5-91e8-c663344098bb.png)
![input_2](https://cloud.githubusercontent.com/assets/14209638/9819829/d8869390-58e2-11e5-9055-0db6b8fa9ce1.png)
![input_3](https://cloud.githubusercontent.com/assets/14209638/9819830/d8868a8a-58e2-11e5-82fa-044784bc12f5.png)

**Comment by romerojosh** [comment]
Hi hzhf,
The issues you are experiencing with these simulations stem from multiple issues.

For the AoA = 0 case:
- When you set dt_type = 0, the timestep is fixed to the dt in the input file (it looks like in this case 1e-7). Due to the highly compressed nature of the flatplate mesh you are running on and the very high flow speed, it is very likely that this is not a stable timestep for this case. Even though you are running uniform flow, violation of this stability constraint can still lead to small numerical perturbations in the field growing uncontrollably. I'd check the magnitude of the timestep you are getting using dt_type = 1, the CFL based timestep. It is probably much smaller than 1e-7. 

For the AoA = -20 case:
It sounds like you are trying to simulate a supersonic wedge with this case. Robust shock capturing is a still an open research topic in high-order methods. There is shock capturing using artificial viscosity available in our code, which you can enable if you provide the right input parameters in your input file (see the end input_naca_shock_visc in the top HiFiLES-solver directory). You can try adding these parameters and see if they work in your case. To explain your results, the reason the x-momentum appears to be constantly growing without blowing up is that, for reasons above, the simulation you are running is unstable. Sometimes, the CFL based timestep (dt_type=1) timestep in cases like this will  become smaller and smaller, causing the code to tend to simply grow towards instability, rather than fully blowing up. 

Try out the artificial viscosity parameters and let us know if that works out for you.

**Comment by hzhf** [comment]
Hi romerojosh
Thanks a lot for your kind and help！

It works when setting very small dt=1.0e-10(dt_type=0) and the residual results are almost zero for AOA=0.0 case.
I would like to try the artificial viscosity  for shock capturing.
Additionally, there are no parameters about pyramid mesh.  Does HiFiLES support pyramid mesh？

Thanks for your answers！

**Comment by mlopez14** [comment]
Not yet, pyramids are not supported.
